name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt update | 
           sudo apt install cmake libeigen3-dev 
    - name: Checkout submodules
      run: git submodule update --init --recursive
    
    - name: Run CMake
      run: |
          mkdir build
          cd build
          cmake ..
    - name: Make
      run: |
           cd build
           make
    - name: Check C++
      run: |
           cd build
           ./main
    - name: Check Python
      run: |
           cd build
           python3 -c "import pykdtree"
