name: Python test pip package

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt update |
           sudo apt install python3-pip -y

    - name: Check Install package from PIP
      run: |
           pip install pydynotree
           pip install numpy
           python3 -c 'import pydynotree'
           python3 -c 'import pydynotree; import numpy as np; tree = pydynotree.TreeR2(); tree.init_tree(); tree.addPoint(np.zeros(2), 0,True); nn = tree.search(np.ones(2)); print("id distance" , nn.id,nn.distance) '
    - name: Python Install Dependencies
      run: |
           pip3 install matplotlib
    - name: Run Python Basic
      run: |
           cd test/python/
           python3 main.py
    - name: Run Python RRT
      run: |
           cd test/python/
           python3 rrt.py
           python3 rrt_free.py
    - name: Run Test all
      run: |
           cd test/python
           python3 all.py
